apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact
    max.compaction.lag.ms: "86400000"
    retention.bytes: "-1"
    retention.ms: "-1"
